### ISSUE TITLE
Tela de cadastro de orçamentos [UI Mobile]

### ISSUE THREAD

**Issue by lucasdemoraesc** [DLL-S/ueg-pecacerta-mobile#2]
Implementar telas referentes ao cadastro de orçamento para a plataforma mobile.

**Comment by danyelliasmanso** [comment]
Vou precisar que me expliquem como está sendo feito no web pra ter uma noção do mobile

**Comment by lucasdemoraesc** [comment]
Não tranquilo mano, ainda não comecei a fazer também 🌚
Já deixei as issues criadas só pra gente ter noção do que precisa ser feito e priorizado. Mas vamos discutir elas ainda.
